//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace trpgRamdom.Properties {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強類型資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建您的 VS 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("trpgRamdom.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強類型資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 
        ///嬌生慣養 INT-1,CON+2
        ///粗壯 SIZ+1
        ///靈敏 DEX+1.當SIZ小於等於9時,靈敏而又嬌小,DEX + 2
        ///時尚 一直注意著衣裝打扮,APP + 1
        ///天才 天生腦袋動得快,INT + 1
        ///意志堅定 不會對POW和SAN帶來變動,但是現在的理智度 + 5點.但是不能超過最大理智度.
        ///努力家 EDU+1.且無視EDU帶來的年齡下限.
        ///幸運的守護符 擁有幸運守護符.只要帶在身邊POW + 1,如果沒帶在身邊就會招來不幸POW - 1. POW的增減會影響幸運,但不會影響理智度.
        ///家傳的寶物 擁有畫卷,書籍,武器,家具等寶物,對於探索者或者故事整體帶來特別的價值.也許寶物是擁有魔法力量的神器
        ///無法預期的協助者 探索者擁有一位對自己盡忠,也許會前來救援的協助者. KP決定協助者是誰,D100決定協助者的影響力.
        ///手指靈活 任意一個“手藝”的基本成功率為50%.且“機械維修”和“電器維修”+10%
        ///存在感弱 一出生就不受人注目. “潛行”和“躲藏”+20 %
        ///有名人之子 “信用”+20 %
        ///藏書者 “圖書館”+20 %.且就算不去圖書館也可以在自己的書庫裡進行“圖書館”判定
        /// [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string featureData {
            get {
                return ResourceManager.GetString("featureData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 15
        ///15
        ///5
        ///5
        ///1
        ///		
        ///20
        ///1
        ///10
        ///10
        ///25
        ///1
        ///5
        ///		
        ///30
        ///1
        ///		
        ///25
        ///25
        ///1
        ///25
        ///20
        ///1
        ///20
        ///15
        ///25
        ///30
        ///
        ///1
        ///1
        ///1
        ///1
        ///1
        ///1
        ///20
        ///1
        ///1
        ///1
        ///1
        ///10
        ///5
        ///5
        ///		
        ///25
        ///25
        ///10
        ///15
        ///1
        ///25
        ///25
        ///10
        ///40
        ///		
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0
        ///0 的當地語系化字串。
        /// </summary>
        internal static string skillInitialValue {
            get {
                return ResourceManager.GetString("skillInitialValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 說服			
        ///信譽度			
        ///心理學					
        ///議價					
        ///變裝
        ///
        ///駕駛汽車			
        ///電腦使用			
        ///電器維修					
        ///攝影					
        ///資料查詢					
        ///操縱【】
        ///手工藝【】					
        ///		
        ///急救			
        ///精神分析			
        ///					
        ///投擲			
        ///空手			
        ///武道					
        ///棍棒					
        ///刀					
        ///居合					
        ///手槍					
        ///衝鋒槍					
        ///來福槍								
        ///閃躲
        ///
        ///物理學			
        ///化學			
        ///考古學					
        ///人類學					
        ///生物學					
        ///天文學					
        ///歷史					
        ///地質學					
        ///藥劑學					
        ///醫學					
        ///神祕學					
        ///會計學					
        ///法律					
        ///藝術【】					
        ///
        ///觀察			
        ///聆聽			
        ///躲藏					
        ///藏東西					
        ///開鎖					
        ///游泳					
        ///跳躍					
        ///追蹤					
        ///攀登					
        ///					
        ///克蘇魯神話						
        ///語言【亞洲語系】					
        ///語言【歐美語系】					
        ///語言【非洲語系】					
        ///語言【古亞洲語】					 [字串的其餘部分已遭截斷]&quot;; 的當地語系化字串。
        /// </summary>
        internal static string skillName {
            get {
                return ResourceManager.GetString("skillName", resourceCulture);
            }
        }
    }
}
